### ISSUE TITLE
Erreur Follow

### ISSUE THREAD

**Issue by AndreVictor60** [JustFS/mern-project#6]
Bonjour,

Je suis débutant sur NodeJS.
Mon probleme s'affiche lorsque j'exécute la méthode follow une erreur apparait :

`TypeError: ({(intermediate value)} , {(intermediate value)(intermediate value)}).then is not a function`
    `at module.exports.follow ..\controllers\user.controller.js:66:10)`
    `at Layer.handle [as handle_request] (..i\node_modules\express\lib\router\layer.js:95:5)`
    `at next (..\node_modules\express\lib\router\route.js:137:13)`
    `at Route.dispatch (..\node_modules\express\lib\router\route.js:112:3)`
    `at Layer.handle [as handle_request] (..\node_modules\express\lib\router\layer.js:95:5)`
    `at ..i\node_modules\express\lib\router\index.js:281:22`
    `at param (..\node_modules\express\lib\router\index.js:354:14)`
    `at param (..\node_modules\express\lib\router\index.js:365:14)`
    `at Function.process_params (..\node_modules\express\lib\router\index.js:410:3)`
    `at next (..\node_modules\express\lib\router\index.js:275:10)`
    `at Function.handle (..i\node_modules\express\lib\router\index.js:174:3)`
    `at router (..\node_modules\express\lib\router\index.js:47:12)`
    `at Layer.handle [as handle_request] (..\node_modules\express\lib\router\layer.js:95:5)`
   ` at trim_prefix (..i\node_modules\express\lib\router\index.js:317:13)`
    `at ..\node_modules\express\lib\router\index.js:284:7`
    `at Function.process_params (..\node_modules\express\lib\router\index.js:335:12)`
    
Voici le code :

    await UserModel.findByIdAndUpdate(
      req.params.id,
      ({ $addToSet: { following: req.body.idToFollow } },
      { new: true, upsert: true })
        .then(data => res.send(data)) // ligne 66
        .catch((err) => {
          console.log("following",err);
          res.status(500).send({ message: err })
        })),

 Et pourtant j'ai repris le code du back sur ce github, si quelqu'un pourrait m'aider ?
 
Merci 👍

**Comment by AndreVictor60** [comment]
J'ai trouve la solution : 

    await UserModel.findByIdAndUpdate(
      req.params.id,
      { $addToSet: { following: req.body.idToFollow } },
      { new: true, upsert: true })
        .then((data) => res.json(data))
        .catch((err) => {
          res.status(500).send({ message: err })
        }),
        
J'avais **( )** en trop ! 👍
